<!-- Message de notification -->

<!-- Code HTML à écrire -->
<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <!-- Code HTML à écrire -->
        <?php foreach($meals as $meal): ?>
         	<tr>
         		<td><a href="#">
         			<img src="/dev/PHP_POO/Resto/Resto/application/www/images/meals/<?= $meal['Photo'] ?>" onerror="this.src='/dev/PHP_POO/Resto/Resto/application/www/images/meals/no-photo.png'"></img></a>
         		</td>
 	        	<td>
 	        		<h3><?= $meal['Name']; ?></h3>
 	        		<?= $meal['Description']; ?>
 	        	</td>
 	        	<td>
 	        		<?= $meal['SalePrice']; ?>
 	        	</td>
 	        </tr>
         <?php endforeach; ?>
    </tbody>
</table>