<h2><i class='fa fa-shopping-cart'></i> Passer une commande</h2>

<form class='generic-form'>
	<fieldset>
		<legend>Ajouter un article</legend>
		<ul>
			<li>
				<label for='nameProduct'>Nom : </label>
				<select id='nameProduct' name='nameProduct'>
					<option>Coca-cola</option>
				</select>
			</li>
			<li>
				<label for='quantity'>Quantité : </label>
				<input id='quantity' type="text" name="quantity">
			</li>
			<li>
				<input class='button button-primary' type="submit" name="save" value="Creer le compte">
			</li>
		</ul>
	</fieldset>
	<fieldset>
		<legend>Récapitulatif de la commande</legend>
		<p>Votre panier est vide</p>
	</fieldset>
	<input class='button button-primary' type="submit" name="save" value="Creer le compte">
	<input class='button button-cancel' type="reset" name="reset" value="Annuler">
</form>