<h2><i class='fa fa-code-fork'></i> Réservation d'une table</h2>

<form class='generic-form'>
	<fieldset>
		<legend>Informations</legend>
		<ul>
			<li>
				<label for='bookingDate'>Date de réservation: </label>
				<select id='bookingDate' name='day'>
					<?php for($i=1; $i<=31; $i++): ?>
					<option><?= $i ?></option>
					<?php endfor; ?>
				</select> /
				<select id='bookingDate' name='month'>
					<option>Janvier</option>
					<option>Février</option>
					<option>Mars</option>
					<option>Avril</option>
					<option>Mai</option>
					<option>Juin</option>
					<option>Juillet</option>
					<option>Août</option>
					<option>Septembre</option>
					<option>Octobre</option>
					<option>Novembre</option>
					<option>Décembre</option>
				</select> /
				<select id='bookingDate' name='year'>
					<?php for($i=2019; $i<=2022; $i++): ?>
					<option><?= $i ?></option>
					<?php endfor; ?>
				</select> À
				<select id='bookingDate' name='hour'>
					<?php for($i=00; $i<24; $i++): ?>
					<option><?= $i ?></option>
					<?php endfor; ?>
				</select> :
				<select id='bookingDate' name='minut'>
					<?php for($i=00; $i<60; $i++): ?>
					<option><?= $i ?></option>
					<?php endfor; ?>
				</select>
			</li>
			<li>
				<label for='nbCustomers'>Nombre de couverts : </label>
				<select id='nbCustomers' type="password" name="nbCustomers">
				<?php for($i=0; $i<=10; $i++): ?>
					<option><?= $i ?></option>
				<?php endfor; ?>
				</select>
			</li>
		</ul>
	</fieldset>
	<input class='button button-primary' type="submit" name="save" value="Creer le compte">
	<input class='button button-cancel' type="reset" name="reset" value="Annuler">
</form>