<h2><i class='fa fa-user'></i> Connexion</h2>

<form class='generic-form'>
	<fieldset>
		<legend><i class='fa fa-lock'></i> Informations d'authenfication</legend>
		<ul>
			<li>
				<label for='mail'>E-mail : </label>
				<input id='mail' type="mail" name="mail">
			</li>
			<li>
				<label for='pass'>Mot de passe : </label>
				<input id='pass' type="password" name="pass">
			</li>
		</ul>
	</fieldset>
	<input class='button button-primary' type="submit" name="save" value="Creer le compte">
	<input class='button button-cancel' type="reset" name="reset" value="Annuler">
</form>